eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:10010/eureka

security:
  env: 1

server:
  port: 8001
spring:
  application:
    name: user
  datasource:
    #    driver-class-name: com.mysql.jdbc.Driver
    #    url: jdbc:mysql://192.168.0.233:3306/MTTDS?serverTimezone=GMT%2B8&characterEncoding=utf-8&rewriteBatchedStatements=true
    #    username: tds
    #    password: tds1234%
    validationQuery: SELECT 1 FROM DUAL
    url: jdbc:mysql://localhost:3306/security?serverTimezone=GMT%2B8&characterEncoding=utf-8&rewriteBatchedStatements=true
#    url: jdbc:mysql://49.233.197.213:3306/hyyt-test?serverTimezone=GMT%2B8&characterEncoding=utf-8&rewriteBatchedStatements=true
    driverClassName:
    username: root
    password: 123456
#    username: hyyttest
#    password: hyyttest
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    #初始化数量
    initialSize: 1
    #最小活跃数
    minIdle: 3
    #最大活跃数
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 20
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
    maxOpenPreparedStatements: 20
    filters: stat,wall,SLF4j
mybatis:
  mapper-locations: classpath:mapping/*.xml
#  type-aliases-package: cn.tjhyyt.common.model.dao
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    org.springframework.security: debug
##jwt配置
#dhb:
#  jwt:
#    # 加密秘钥
#    secret: f4e2e52034348f86b67cde581c0f9eb5
#    # token有效时长，7天，单位秒
#    expire: 604800

#    header: authorization